name: Build and deploy to gh-pages

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container: nopreserveroot/latexmk

    steps:
    - uses: actions/checkout@v3
    
    - name: Install packages
      run: |
        apt-get update
        apt-get install make wget
        
    - name: Donwload fonts
      run: |
        wget https://github.com/ernestchu/cv/releases/download/fonts/fonts.tar.gz
        tar xzf fonts.tar.gz
    
    - name: Install fonts
      run: |
        mkdir -p ~/.local/share/fonts
        cp -r fonts/* ~/.local/share/fonts/
        fc-cache -rv

    - name: Build
      run: make

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        
