name: Build Typst document
on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  compile_pdf_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Donwload fonts
        run: |
          wget https://github.com/ernestchu/cv/releases/download/fonts/fonts.tar.gz
          tar xzf fonts.tar.gz

      - name: Install Typst
        uses: typst-community/setup-typst@v4

      - name: Compile pdf
        run: typst c cv.typ --font-path fonts

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .

